# Generated by Django 2.2 on 2021-07-07 21:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Coigo')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'inventario_marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precio')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'inventario_producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('unidades', models.IntegerField(default=0, verbose_name='Unidades')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad Medida')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'pesentacion',
                'verbose_name_plural': 'presentaciones',
                'db_table': 'inventario_presentacion',
                'managed': True,
            },
        ),
    ]
